### ISSUE TITLE
post profie not working

### ISSUE THREAD

**Issue by zaki43** [lvamsavarthan/Hify#1]
posts profie not working

**Comment by MorRsvps** [comment]
where can i find FIREBASE_AUTH_KEY?

**Comment by lvamsavarthan** [comment]
Can you please explain clearly what is not working?

**Comment by lvamsavarthan** [comment]
> where can i find FIREBASE_AUTH_KEY?

Where am I using FIREBASE_AUTH_KEY in the app?

**Comment by lvamsavarthan** [comment]
**set your firebase firestore rules as following and try**

service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth!=null;
    }
    match /Usernames/{Usernames} {
      allow read;
    }
  }
}

**Comment by zaki43** [comment]
Oooh tanks bro 😎 is working.👈🤜✊🙌🙌

**Comment by Samson11** [comment]
When I open my profile to see my post I get an unexpected error
