### ISSUE TITLE
Some layout and Java classes missing

### ISSUE THREAD

**Issue by IamKanwarpartapSingh** [lvamsavarthan/Hify#10]
After saw all files and putting into the android studio it shows that some error and they proved some files missing by you. Why you do this. please don't do this. @Github allows you to put all source code in it.

**Comment by IamKanwarpartapSingh** [comment]
Now I had check and see its working good. but please convey me swipeable folder's purpose in this app. I need in it or not?

**Comment by IamKanwarpartapSingh** [comment]
I had checked it. Now found missed **_Drawables_** and **_Layouts_** also. This is shown in values folder where you post XML folder and files. There is missing **_Drawable_** and a **_Layouts_** and **_Strings_** values.
Thanks

**Comment by lvamsavarthan** [comment]
Include logs

**Comment by lvamsavarthan** [comment]
Include the error logs

**Comment by lvamsavarthan** [comment]
I have re-uploaded the full project again except google-services.json
