### ISSUE TITLE
Problem with firebase deploy

### ISSUE THREAD

**Issue by AbirFFA** [lvamsavarthan/Hify#14]
Can not deploy

- CMD
![image](https://user-images.githubusercontent.com/42368238/51050502-36b02980-15fb-11e9-8c2e-3e9fd70f7782.png)

- firebase.json
[firebase__json.txt](https://github.com/lvamsavarthan/Hify/files/2750625/firebase__json.txt)

- index.js
[index_js.txt](https://github.com/lvamsavarthan/Hify/files/2750627/index_js.txt)

- Log 
[log.txt](https://github.com/lvamsavarthan/Hify/files/2750652/log.txt)

**Comment by lvamsavarthan** [comment]
Have you checked out the tutorial from my youtube channel for setting up the cli

**Comment by AbirFFA** [comment]
Yeah

**Comment by lvamsavarthan** [comment]
Do not deploy the code from cloudfunctions folder directly into index.js file. First copy the below code by changing the required parameters from each txt file in cloud functions

'use-strict'

const functions = require('firebase-functions');

const admin=require('firebase-admin');

admin.initializeApp(functions.config().firebase);

exports.<function_name>=functions.firestore.document("<function_document_path>").onWrite((change,context)=> {

console.log("Notification Sent.");

});

Then change the code from the cloud functions dashboard from firebase
