### ISSUE TITLE
GetToken is deprecated

### ISSUE THREAD

**Issue by Moh09** [lvamsavarthan/Hify#17]
Hello, 
First thanks a lot for this application, it helped me to understand many things!

My issue : 
GetToken() is deprecated 

`String token_id = FirebaseInstanceId.getInstance().getToken();`

And I don't know for sure how to change it, like this : 

`Task<InstanceIdResult> token_id = FirebaseInstanceId.getInstance().getInstanceId(); `

Thanks in advance for any help.

**Comment by lvamsavarthan** [comment]
Yeah FirebaseInstanceIdService is depreciated. You need to make a small change to the FCMService.java by overriding a new function such as

```
@Override
public void onNewToken(String s) {
    super.onNewToken(s);
    Log.d("NEW_TOKEN",s);
}

```

**Comment by lvamsavarthan** [comment]
I have updated the code according to the recent Firebase changes 👍.
