### ISSUE TITLE
Cloud Functions not Notifying

### ISSUE THREAD

**Issue by AxesandGrinds** [lvamsavarthan/Hify#20]
Hello Amsavarthan,

Please, I need your help. Cloud functions not cause push notifications (alerter) to show any messages that a comment has been made or that a user has liked a page. On Firebase Functions Console loh, I am seeing that my notifications are being sent. But I get no notification on the phone.

Attached are my main activity and my FCMService. Please advise. Let me know if there are any other files you need.

[HifyNotifNotWorking.zip](https://github.com/lvamsavarthan/Hify/files/3035950/HifyNotifNotWorking.zip)

**Comment by AxesandGrinds** [comment]
So, in order to troubleshoot why the notifications are not being sent to my app, I edited the sendCommentNotification file with the following ending lines:

        
             
             // Send a message to devices subscribed to the provided topic.
             return admin.messaging().sendToDevice(admin_token,payload).then(function (response) {
            // See the MessagingTopicResponse reference documentation for the
            // contents of response.
            console.log("Successfully sent message:", response);
            return;
            })
            .catch(function (error) {
                console.log("Error sending message:", error);
            });

From there, I was able to get the error message in firebase functions log:

Successfully sent message: { results: [ { error: [Object] } ],
  canonicalRegistrationTokenCount: 0,
  failureCount: 1,
  successCount: 0,
  multicastId: 7952971403531609000 }

This means that the functions are not going through. Please look into this and check if your code is successfully allowing notifications (alerter) and update me accordingly the change in code?

Thank you.

**Comment by AxesandGrinds** [comment]
When I view the error message on firebase cloud functions log, I get the following. Please help.

Error:  { Error: The provided registration token is not registered. A previously valid registration token can be unregistered for a variety of reasons. See the error documentation for more details. Remove this registration token and stop using it to send messages.
    at FirebaseMessagingError.Error (native)
    at FirebaseMessagingError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:88:28)
    at new FirebaseMessagingError (/user_code/node_modules/firebase-admin/lib/utils/error.js:253:16)
    at Function.FirebaseMessagingError.fromServerError (/user_code/node_modules/firebase-admin/lib/utils/error.js:283:16)
    at /user_code/node_modules/firebase-admin/lib/messaging/messaging.js:381:63
    at Array.forEach (native)
    at mapRawResponseToDevicesResponse (/user_code/node_modules/firebase-admin/lib/messaging/messaging.js:377:26)
    at /user_code/node_modules/firebase-admin/lib/messaging/messaging.js:558:24
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  errorInfo: 
   { code: 'messaging/registration-token-not-registered',
     message: 'The provided registration token is not registered. A previously valid registration token can be unregistered for a variety of reasons. See the error documentation for more details. Remove this registration token and stop using it to send messages.' },
  codePrefix: 'messaging' }

**Comment by AxesandGrinds** [comment]
Please view this same question on Stackoverflow that I posted. https://stackoverflow.com/questions/55545542/firebase-cloud-functions-tokens

Please let me know exactly how to edit the cloud functions (node.js) files in order to remove expired tokens.

Thank you.

**Comment by AxesandGrinds** [comment]
I have gotten some response from Stackoverflow but I don't know how to update your code in order to fit the model that allows for storing multiple tokens and then deleting the ones that later on produce an error..

https://github.com/firebase/functions-samples/blob/Node-8/fcm-notifications/functions/index.js#L72-L88

**Comment by lvamsavarthan** [comment]
Now the Firebase device token will be automatically synced with the server. I found that Firebase InstanceId service has been depreciated so I have updated it ✌️. Cheers

**Comment by AxesandGrinds** [comment]
I'm telling you that your simple update doesn't fix the problem. In actuality, the Server has to maintain more than just one token per user. A token is developed per device of the user so if the user has multiple devices from which he access your app then each device has to have a separate token. 

One of the big problems is that you do not save the registration token. That has to be saved to token array in cloud.

That truth is detailed her on how to manage multiple tokens: https://github.com/firebase/functions-samples/blob/master/fcm-notifications/functions/index.js

Secondly, in order to manage more than one token at a time per user, you need to change the following files: RegisterActivity, LoginActivity, FriendProfile, Friends, FriendRequest, AddFriendAdapter, SearchFriendAdapter, FCMService, Manifest should be changed to nolonger use InstanceIdService.

Then lastly you have to update your cloud functions from a singular string token to an array of tokens in case if user has multiple devices used at once and wants to be synchronized between all devices.

I have updated your code to now be checking for multiple tokens. I will post the affected files and the updated cloud functions by tomorrow.

**Comment by AxesandGrinds** [comment]
I fixed all the issues. It only took a few weeks. I'm closing this issue. In another issue, I answer my files.
