### ISSUE TITLE
Cloud Functions and Notifications now working

### ISSUE THREAD

**Issue by AxesandGrinds** [lvamsavarthan/Hify#21]
Hi Amsavarthan,

I have edited some of your files and now I can say that cloud functions and notifications are now working. The problem with the notifications was your understanding of channels. Channels need to be set just once and so does not have to be part of the notificationmessage functions in NotificationUtil every time it is called. Channels are not retrieved from the cloud either. It just happens once each time the activity is started. Secondly, your cloud functions didn't have any method of detecting errors. In your code, whether or not the function is successful or failed both showed up as successful. I changed that. I also added a method for the cloud to delete inactive tokens but that is assuming that you would be interested in my multiple token per user adaptation. You obviously don't have to completely trade in my adjusted java files with your code. But if you read through it, you will see the things I changed that got Notifications and Cloud functions working.

Victor
[Iv.zip](https://github.com/lvamsavarthan/Hify/files/3122860/Iv.zip)

**Comment by lvamsavarthan** [comment]
Thank you @AxesandGrinds 🥰
