### ISSUE TITLE
App stuck on login activity

### ISSUE THREAD

**Issue by ahmedibrahim10** [lvamsavarthan/Hify#25]
When i put my registered email it shows me please wait window and it does not move to the rest of the app

**Comment by ahmedibrahim10** [comment]
do you mean that i can't use my own google-service.json and debug the app
as an apk ?

**Comment by Muhammadtawil** [comment]
How its work? I have same error

**Comment by Vico231088** [comment]
They must activate cloud firestore so that their user is created
