### ISSUE TITLE
Sign Up error

### ISSUE THREAD

**Issue by thikill** [lvamsavarthan/Hify#27]
**Describe the bug**
2019-06-02 19:12:55.732 6755-6755/com.amsavarthan.hify E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amsavarthan.hify, PID: 6755
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amsavarthan.hify/com.amsavarthan.hify.ui.activities.account.RegisterActivity}: java.lang.IllegalArgumentException: invalid provider: null

**To Reproduce**
1. Go to Login screen
2. Click on Sign up
3. Scroll down to 'Logcat'

**Comment by lvamsavarthan** [comment]
Take a look at this [Issue#6](https://github.com/lvamsavarthan/Hify/issues/6#issuecomment-431351602)
