### ISSUE TITLE
App crash in Posts Fragment - watching likes

### ISSUE THREAD

**Issue by chaimleu** [lvamsavarthan/Hify#30]
When watching a post and click the "analytics" button which show the likes the app crash immediately. 

Exact Error is:
"java.lang.NullPointerExecption: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference at com.lvamsavarthan.hify.adapters.PostsAdapter.lambda$null$29$PostsAdapter(PostsAdapter.java:469"

**Comment by DeekshithRajBasa** [comment]
It is an Exception so, probably it might have bug.

**Comment by alsong** [comment]
________________________________
