### ISSUE TITLE
App cannot login or register. Stuck at please wait... Please help

### ISSUE THREAD

**Issue by ayabz** [lvamsavarthan/Hify#38]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lvamsavarthan** [comment]
Take a look at this [Issue#6](https://github.com/lvamsavarthan/Hify/issues/6#issuecomment-431351602)

**Comment by mowet601** [comment]
Issue#6 don't seem to be working for me
