### ISSUE TITLE
"Some Technical Error Occurred" on clicking Posts in Profiles

### ISSUE THREAD

**Issue by orion254** [lvamsavarthan/Hify#39]
Hey @lvamsavarthan On clicking view profile( MYPROFILE ), I Can't View My Posts after clicking (POSTS) icon at the bottom, or when i try to view my friends post on their Profile by clicking their (Posts) on the Bottom, it throws "Some Technical Error Occurred".Anyone help.
The rest works super fine.

**Comment by Rezureax** [comment]
I have the same error.Do you have a solution?

**Comment by snajdovski** [comment]
1)Connect your phone or open a Virtual Device
2)Compile Debug App
3)Try to open posts from the profile
4) See log
5)Click on the link that it is generated for the query
6)Wait some time
7)Done
