### ISSUE TITLE
Post clicking on registration App is not moving forward

### ISSUE THREAD

**Issue by sraghudatta94** [lvamsavarthan/Hify#6]
Hi savarthan,

I have cloned project and tried building and running it. I have added googleservices.json to app folder enabling email auth in firebase console. When i try to run app, post giving details of user and profile photo i am unable to navigate further. Need ur help

Thanks,
Raghu Datta

**Comment by lvamsavarthan** [comment]
**Modify the firebase firestore rules as below**

service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth!=null;
    }
    match /Usernames/{Usernames} {
      allow read;
    }
  }
}

**Comment by sraghudatta94** [comment]
This works like a charm. Thanks @lvamsavarthan
