### ISSUE TITLE
Setting up cloud functions

### ISSUE THREAD

**Issue by okchans** [lvamsavarthan/Hify#7]
Tutorial for uploading cloud functions code please

**Comment by lvamsavarthan** [comment]
Errors log please

**Comment by okchans** [comment]
I did not get an error, but I do not know how to set the cloud_function

**Comment by snajdovski** [comment]
Same don't know how I can set the cloud functions, I wanna test this app it looks very modern and very well built

**Comment by lvamsavarthan** [comment]
Mmm will upload a tutorial and send the link asap 😊

**Comment by snajdovski** [comment]
Also a great help would be how to setup firebase and all its rules and things like that

**Comment by okchans** [comment]
Thank you! 😊

**Comment by lvamsavarthan** [comment]
Here is the tutorial 
Part - 1 : [Setting up Firebase CLI](https://youtu.be/-T-yGL1qRho)
Part - 2 : [Deploying to Firebase Cloud Functions](https://youtu.be/3fBiSJB-i_E)
