### ISSUE TITLE
I got an error on my Samsung Galaxy device. (Galaxy A7 2017)

### ISSUE THREAD

**Issue by okchans** [lvamsavarthan/Hify#8]
2018-11-23 23:31:03.270 2149-5201/kr.oklabs.hify E/AndroidRuntime: FATAL EXCEPTION: Firebase-FCMService
    Process: kr.oklabs.hify, PID: 2149
    java.lang.NullPointerException: println needs a message
        at android.util.Log.println_native(Native Method)
        at android.util.Log.e(Log.java:312)
        at kr.oklabs.hify.utils.NotificationUtil.showNotificationMessage(NotificationUtil.java:128)
        at kr.oklabs.hify.receivers.FCMService.showNotificationMessage(FCMService.java:276)
        at kr.oklabs.hify.receivers.FCMService.handleDataMessage(FCMService.java:182)
        at kr.oklabs.hify.receivers.FCMService.onMessageReceived(FCMService.java:40)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:60)
        at com.google.firebase.iid.zzg.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)

**Comment by lvamsavarthan** [comment]
Which line it's point to?

**Comment by okchans** [comment]
NotificationUtil.java:128

public class NotificationUtil {
    private static String TAG = NotificationUtil.class.getSimpleName();

    private Context mContext;

    public NotificationUtil(Context mContext) {
        this.mContext = mContext;
    }

    public static void clearNotifications(Context context) {
        NotificationManager notificationManager = (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);
        notificationManager.cancelAll();
    }

    public static void clearNotificationsById(Context context, int id) {
        NotificationManager notificationManager = (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);
        notificationManager.cancel(id);
    }

    public static long getTimeMilliSec(String timeStamp) {
        @SuppressLint("SimpleDateFormat") SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        try {
            Date date = format.parse(timeStamp);
            return date.getTime();
        } catch (ParseException e) {
            e.printStackTrace();
        }
        return 0;
    }

    public void showNotificationMessage(int id, String timeStamp, String click_action, String channelName, String channelDesc, String user_image, String title, String message, Intent intent) {
        showNotificationMessage(id, timeStamp, click_action, channelName, channelDesc, user_image, title, message, intent, null);
    }

    @RequiresApi(api = Build.VERSION_CODES.O)
    private void setupChannels(NotificationManager notificationManager, String channelName, String channelDesc) {
        NotificationChannel adminChannel;
        adminChannel = new NotificationChannel(Config.ADMIN_CHANNEL_ID, channelName, NotificationManager.IMPORTANCE_HIGH);
        adminChannel.setDescription(channelDesc);
        adminChannel.enableLights(true);
        adminChannel.setLightColor(Color.BLUE);
        adminChannel.canShowBadge();
        adminChannel.setImportance(NotificationManager.IMPORTANCE_HIGH);
        adminChannel.enableVibration(true);
        if (notificationManager != null) {
            notificationManager.createNotificationChannel(adminChannel);
        }
    }

    public void showNotificationMessage(int id, String timeStamp, String click_action, String channelName, String channelDesc, final String user_image, final String title, final String message, Intent intent, String imageUrl) {

        // Check for empty push message
        if (TextUtils.isEmpty(message))
            return;

        // notification icon
        final int icon = R.mipmap.ic_launcher;

        intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_SINGLE_TOP);
        final PendingIntent resultPendingIntent =
                PendingIntent.getActivity(
                        mContext,
                        0,
                        intent,
                        PendingIntent.FLAG_CANCEL_CURRENT
                );

        final NotificationCompat.Builder mBuilder = new NotificationCompat.Builder(
                mContext, Config.ADMIN_CHANNEL_ID);


        try {
            if (!TextUtils.isEmpty(imageUrl)) {

                Bitmap bitmap = getBitmapFromURL(imageUrl);


                if (bitmap != null) {
                    showBigNotification(id, timeStamp, click_action, channelName, channelDesc, user_image, bitmap, mBuilder, icon, title, message, resultPendingIntent);
                } else {
                    showSmallNotification(id, timeStamp, click_action, channelName, channelDesc, user_image, mBuilder, icon, title, message, resultPendingIntent);
                }

            } else {
                showSmallNotification(id, timeStamp, click_action, channelName, channelDesc, user_image, mBuilder, icon, title, message, resultPendingIntent);
            }
        } catch (Exception e) {
            **Log.e("showNotificationMessage", e.getMessage());**
        }


    }

    public Intent getIntent(String click_action) {

        Intent resultIntent;

        switch (click_action) {
            case "com.oklabs.hify.TARGETNOTIFICATION":
                resultIntent = new Intent(mContext, NotificationActivity.class);
                break;
            case "com.oklabs.hify.TARGETNOTIFICATIONREPLY":
                resultIntent = new Intent(mContext, NotificationReplyActivity.class);
                break;
            case "com.oklabs.hify.TARGETNOTIFICATION_IMAGE":
                resultIntent = new Intent(mContext, NotificationImage.class);
                break;
            case "com.oklabs.hify.TARGETNOTIFICATIONREPLY_IMAGE":
                resultIntent = new Intent(mContext, NotificationImageReply.class);
                break;
            case "com.oklabs.hify.TARGET_FRIENDREQUEST":
                resultIntent = new Intent(mContext, FriendProfile.class);
                break;
            default:
                resultIntent = new Intent(mContext, MainActivity.class);
                break;
        }
        return resultIntent;

    }

    private void showSmallNotification(int id, String timeStamp, String click_action, String channelName, String channelDesc, String user_image, NotificationCompat.Builder mBuilder, int icon, String title, String message, PendingIntent resultPendingIntent) {
        NotificationManager notificationManager = (NotificationManager) mContext.getSystemService(Context.NOTIFICATION_SERVICE);

        NotificationCompat.BigTextStyle bigTextStyle = new NotificationCompat.BigTextStyle();
        bigTextStyle.setBigContentTitle(title);
        bigTextStyle.bigText(message);


        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            setupChannels(notificationManager, channelName, channelDesc);
        }

        Notification notification;
        notification = mBuilder.setSmallIcon(icon).setTicker(title).setWhen(0)
                .setAutoCancel(true)
                .setContentTitle(title)
                .setContentIntent(resultPendingIntent)
                .setColorized(true)
                .setWhen(getTimeMilliSec(timeStamp))
                .setShowWhen(true)
                .setSound(Uri.parse("android.resource://"+mContext.getPackageName()+"/"+R.raw.hify_sound))
                .setColor(Color.parseColor("#2591FC"))
                .setStyle(bigTextStyle)
                //.addPerson(user_image)
                //.setLargeIcon(getBitmapFromURL(user_image))
                .setSmallIcon(R.mipmap.ic_launcher)
                .setContentText(message)
                .build();

        notificationManager.notify(id, notification);
    }

    private void showBigNotification(int id, String timeStamp, String click_action, String channelName, String channelDesc, String user_image, Bitmap bitmap, NotificationCompat.Builder mBuilder, int icon, String title, String message, PendingIntent resultPendingIntent) {

        NotificationManager notificationManager = (NotificationManager) mContext.getSystemService(Context.NOTIFICATION_SERVICE);

        NotificationCompat.BigPictureStyle bigPictureStyle = new NotificationCompat.BigPictureStyle();
        bigPictureStyle.setBigContentTitle(title);
        bigPictureStyle.bigPicture(bitmap);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            setupChannels(notificationManager, channelName, channelDesc);
        }

        Notification notification;

        notification = mBuilder.setSmallIcon(icon).setTicker(title).setWhen(0)
                .setAutoCancel(true)
                .setContentTitle(title)
                .setContentIntent(resultPendingIntent)
                .setColorized(true)
                .setShowWhen(true)
                .setSound(Uri.parse("android.resource://"+mContext.getPackageName()+"/"+R.raw.hify_sound))
                .setWhen(getTimeMilliSec(timeStamp))
                .setColor(Color.parseColor("#2591FC"))
                .setStyle(bigPictureStyle)
                //.setLargeIcon(getBitmapFromURL(user_image))
                .setSmallIcon(R.mipmap.ic_launcher)
                //.addPerson(user_image)
                .setContentText(message)
                .build();

        notificationManager.notify(id, notification);
    }

    private Bitmap getBitmapFromURL(String strURL) {
        try {
            URL url = new URL(strURL);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setDoInput(true);
            connection.connect();
            InputStream input = connection.getInputStream();
            return BitmapFactory.decodeStream(input);
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

}

**Comment by okchans** [comment]
Look at the code here.
NotificationUtil.java:128
FCMService.java:276
FCMService.java:182
FCMService.java:40

[Code.zip](https://github.com/lvamsavarthan/Hify/files/2615131/Code.zip)

**Comment by lvamsavarthan** [comment]
Just add +".. " to log text like
```
Log.i(TAG, already existing variable+"...
 ");
```

**Comment by okchans** [comment]
Where do you type this?

**Comment by lvamsavarthan** [comment]
@okchans at these lines

**Comment by okchans** [comment]
Notifications are not coming after adding code

**Comment by okchans** [comment]
Is the firebase plan Blaze?

**Comment by lvamsavarthan** [comment]
No need Firebase blaze plan, setup the cloud functions code correctly
Video tutorial : https://www.youtube.com/watch?v=-T-yGL1qRho
